In [1]:
import pandas as pd

In [8]:
first = pd.read_csv(r'C:\Users\Janek\Otomoto.pl\Rawgolf.csv')
first

,Unnamed: 0,ID,Price,Predict_Low,Predict_High,Location,Oferta od,Kategoria,Marka pojazdu,Model pojazdu,...,HUD (wyświetlacz przezierny),Podgrzewane tylne siedzenia,Odtwarzacz DVD,Ogrzewanie postojowe,Radio niefabryczne,Światła Xenonowe,Hak,Klimatyzacja czterostrefowa,Zmieniarka CD,Tuner TV
0,0,6.077535e+09,11900.0,11 250,13 100,NaN,Osoby prywatnej,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,6.070865e+09,14500.0,11 450,13 300,NaN,Osoby prywatnej,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6.076245e+09,81900.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,6.072484e+09,68900.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6.072485e+09,69500.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4757,4757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4758,4758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4759,4759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4760,4760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4761,4761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
second = pd.read_csv(r'C:\Users\Janek\Otomoto.pl\RawGolf2.csv')
first

,Unnamed: 0,ID,Price,Predict_Low,Predict_High,Location,Oferta od,Kategoria,Marka pojazdu,Model pojazdu,...,HUD (wyświetlacz przezierny),Podgrzewane tylne siedzenia,Odtwarzacz DVD,Ogrzewanie postojowe,Radio niefabryczne,Światła Xenonowe,Hak,Klimatyzacja czterostrefowa,Zmieniarka CD,Tuner TV
0,0,6.077535e+09,11900.0,11 250,13 100,NaN,Osoby prywatnej,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,6.070865e+09,14500.0,11 450,13 300,NaN,Osoby prywatnej,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6.076245e+09,81900.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,6.072484e+09,68900.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6.072485e+09,69500.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4757,4757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4758,4758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4759,4759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4760,4760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4761,4761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
joined = pd.concat?

In [ ]:
joined = pd.concat

In [17]:
joined = pd.concat([first,second],
                 join = 'outer',
                  ignore_index = True)
joined

,Unnamed: 0,ID,Price,Predict_Low,Predict_High,Location,Oferta od,Kategoria,Marka pojazdu,Model pojazdu,...,HUD (wyświetlacz przezierny),Podgrzewane tylne siedzenia,Odtwarzacz DVD,Ogrzewanie postojowe,Radio niefabryczne,Światła Xenonowe,Hak,Klimatyzacja czterostrefowa,Zmieniarka CD,Tuner TV
0,0,6.077535e+09,11900.0,11 250,13 100,NaN,Osoby prywatnej,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,6.070865e+09,14500.0,11 450,13 300,NaN,Osoby prywatnej,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6.076245e+09,81900.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,6.072484e+09,68900.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6.072485e+09,69500.0,NaN,NaN,"Niciarniana 51/53 - 92-320 Łódź, Łódzkie (Polska)",Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9468,4706,6.002450e+09,NaN,NaN,NaN,NaN,Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
9469,4707,6.001729e+09,NaN,NaN,NaN,NaN,Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
9470,4708,6.001729e+09,NaN,NaN,NaN,NaN,Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9471,4709,6.001723e+09,NaN,NaN,NaN,NaN,Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9472,4710,4.035604e+09,NaN,NaN,NaN,NaN,Firmy,Osobowe,Volkswagen,Golf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
joined.to_csv(r'C:\Users\Janek\Otomoto.pl\merged_golf.csv')